services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "80:80"
    environment:
      APP_PORT: ${APP_PORT}
      API_PORT: ${API_PORT}
    volumes:
      - ./${APP_ENV:-production}.conf:/etc/nginx/templates/default.conf.template
      - ${SSL_CERT}:/ssl/cert.crt
      - ${SSL_KEY}:/ssl/private.key
      - ./web/dist:/www:ro
    depends_on:
      - "web"
      - "api"

  web:
    image: node:16-alpine
    command: >
      sh -c "
        cd /@web &&
        if [ ${APP_ENV} == 'development' ]; then
          npm run dev
        else
          npm run build
        fi
      "
    environment:
      NODE_ENV: ${APP_ENV:-production}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./web:/@web

  api:
    image: node:16-alpine
    command: >
      sh -c "
        cd /@api &&
        if [ ${APP_ENV} == 'development' ]; then
          npm run dev
        else
          npm run start
        fi
      "
    environment:
      NODE_ENV: ${APP_ENV:-production}
      API_PORT: ${API_PORT}
      DB_PATH: "mongodb://mongodb:27017/${DB_DATABASE}"
    volumes:
      - ./api:/@api

  mongodb:
    image: mongo:4.4
    volumes:
      - ~/.mongodb:/var/lib/mongodb
