services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./${APP_ENV}.conf:/etc/nginx/templates/default.conf.template
      - ${SSL_CERT}:/ssl/cert.crt
      - ${SSL_KEY}:/ssl/private.key
      - ./web/dist:/www:ro

  web:
    container_name: web
    image: node:16-alpine
    command: >
      sh -c "
        cd /@dev &&
        if [ ${APP_ENV} == 'production' ]; then
          npm run build
        else
          npm run dev
        fi
      "
    env_file:
      - .env
    volumes:
      - ./web:/@dev

  # OLD WEB
  # web:
  #   container_name: web
  #   build:
  #     context: ./web
  #     target: ${APP_ENV}
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./web:/@dev
  #     - ./www:/www

  api:
    container_name: api
    build:
      context: ./api
      target: ${APP_ENV}
    env_file:
      - .env
    volumes:
      - ./api:/@dev

  db:
    container_name: db
    image: mongo:4.4
    volumes:
      - ~/.mongodb:/var/lib/mongodb
