services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "80:80"
    environment:
      APP_PORT: ${APP_PORT}
      API_PORT: ${API_PORT}
    volumes:
      - ./${APP_ENV:-production}.conf:/etc/nginx/templates/default.conf.template
      - ${SSL_CERT}:/ssl/cert.crt
      - ${SSL_KEY}:/ssl/private.key
      - ./web/dist:/www:ro
    depends_on:
      - "web"
      - "api"

  web:
    image: node:16-alpine
    command: >
      sh -c "
        cd /@web &&
        if [ ${APP_ENV} == 'development' ]; then
          npm run dev
        else
          npm run build
        fi
      "
    environment:
      TAILWIND_TOUCH_DIR: /@web/.tailwindcss
      NODE_ENV: ${APP_ENV:-production}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./web:/@web

  api:
    image: node:16-alpine
    command: >
      sh -c "
        cd /@api &&
        if [ ${APP_ENV} == 'development' ]; then
          npm run dev
        else
          npm run start
        fi
      "
    environment:
      NODE_ENV: ${APP_ENV:-production}
      PORT: ${API_PORT}
      MONGODB_URL: "mongodb://mongodb:27017/${DB_DATABASE}"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}
    ports:
      - "5000:5000"
    volumes:
      - ./api:/@api

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/var/lib/mongodb

volumes:
  mongodb:
    driver: local
